version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"  # Si tu aplicación web corre en este puerto

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
